### PR TITLE
Adding "I am the captain now" template

### PR DESCRIPTION
**Pull request by ThomasWo**
Issue #98 has been open for WAY too long, so I fix.

### CODE REVIEW

**Comment by CptSpaceToaster** [comment]
The template you pushed doesn't seem to match the template used in examples of this meme... are you sure you want the image you chose?

Expected

versus

Given

**Comment by ThomasWo** [comment]
Ah, you're right!  I was trying to find a good quality picture from that scene and that one seemed to be close enough, but I just found another one that matched the example.  PTAL

Not sure why Travis CI is failing, the ```make validate``` check passes on my machine.  Travis is failing on validate for the Johnny Ive template, which specifically passes on my machine:

```
...
INFO: checking template 'ive' ...
INFO: link already checked: http://www.quickmeme.com/Jony-Ive
INFO: checking alias 'jony' -> 'ive' ...
INFO: checking alias 'best-thing-ever' -> 'ive' ...
INFO: checking template 'toohigh' ...
...
```

**Comment by jacebrowning** [comment]
QuickMeme is down right now: http://www.quickmeme.com/Jony-Ive

**Comment by jacebrowning** [comment]
That validator caches previous checks to avoid making a bunch of requests locally, but Travis CI always checks every link.

**Comment by ThomasWo** [comment]
@jacebrowning quickmeme is (finally) back up and validator is in the green, please take another look.

**Pull request merged**
