### PR TITLE
add loading gif while meme loads

### LINKED ISSUE #196: Add a placeholder loading indicator for images
The site will look nicer if it shows a loading animation for images.

### PR DESCRIPTION
**Pull request by GusCaplan**
There is no reason this shouldn't work, but I when I tried to test this, It turned out (pls no hate) that my internet is too fast. I wasn't able to see what happened when memes were loading because it happened too fast. But, i've used this method before, and it has worked.

Also, closes #196 

- [x] make loading gif show when images are loading

### CODE REVIEW

**Comment by jacebrowning** [comment]
One possible way to test this is to simulate high latency using Chrome developer tools:

screen shot 2016-05-27 at 9 44 39 am

I'll check it out...

**Comment by GusCaplan** [comment]
Nice I didn't know that. Useful.

**Comment by jacebrowning** [comment]
I'm not seeing any loading GIFs with the deployed Heroku review app and simulated latency:

screen shot 2016-05-27 at 10 06 51 am

**Comment by GusCaplan** [comment]
I will do some code things and work on this. Stay tuned

**Comment by GusCaplan** [comment]
Alright! everything is working now!

**Comment by jacebrowning** [comment]
Can you attach a screenshot of what the spinner looks like when the page is loading? I still just see an empty white background as the grid of images loads.

Also, you need to rebase on `master`. ♻️

**Comment by GusCaplan** [comment]
@jacebrowning when i squashed i used the wrong head and overwrote my changes :)

**Comment by GusCaplan** [comment]
im going to open another one with the final code things

**Pull request closed without merging**
