### PR TITLE
Add a worker to generate default images

### PR DESCRIPTION
**Pull request by jacebrowning**

### CODE REVIEW

**Comment by joshfriend** [comment]
Heroku dynos have an [ephemeral filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) which is not shared between dynos. Thus, the images the workers generates will not be available to the web dynos.

**Comment by jacebrowning** [comment]
Can you demonstrate that on the PR deploy?

**Comment by jacebrowning** [comment]
What if the worker simply requested URLs from the main site periodically?

**Comment by jacebrowning** [comment]
@joshfriend Would it make sense to do this during `bin/post_compile`?

**Comment by joshfriend** [comment]
I don't think so since that would only run on a deploy, but workers get restarted daily. Maybe [heroku scheduler](https://elements.heroku.com/addons/scheduler) would work?

**Comment by jacebrowning** [comment]
@joshfriend But wouldn't that make images part of the Slug?

**Comment by joshfriend** [comment]
I guess that would work. You'd just have to be careful of the 300MB slug size limit (someday).

**Pull request merged**
