### PR TITLE
Improve look & feel of site

### PR DESCRIPTION
**Pull request by jasich**
- [x] Add back in Google Analytics Tracker
- [x] Remove unused pages (overview & generator)
- [ ] Move & cleanup inline JavaScript 
- [ ] Cleanup/Refactor CSS
- [x] Make footer links work
- [ ] Extract common site theme to apply to other pages (e.g. latest)
- [x] Get proper top & bottom text shown as templates change in generator
- [ ] Use more columns on wide screens
- [x] Change typeahead text to a color better than white :person_frowning: 
- [x] Copy the existing homepage content to the README or other docs
- [x] Support empty fields when generating images
- [ ] Increase the width and height of the templates dropdown
- [ ] Wrap the text under images in the grid at the width of the image

### CODE REVIEW

**Comment by jacebrowning** [comment]
From @joshfriend on the other PR:

> :sparkles: :cake: :sparkles: 

> The meme selector dropdown is pretty great :)

> If you don't specifically enter `_` as the text for top/bottom to make one blank, the generate button does nothing.

**Comment by jacebrowning** [comment]
@jasich @joshfriend From my perspective, this is now functionally complete and the remaining tasks are code and UI styling tasks. I'm tempted to merge this now and move the tasks to GitHub issues.

Thoughts? Is there anything else that needs happen before that?

**Comment by jasich** [comment]
Running `make run` I get 
`sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "memes" already exists
 [SQL: '\nCREATE TABLE memes (\n\tid SERIAL NOT NULL, \n\tkey VARCHAR NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n']`

I know it's probably nothing to do with the PR, but is there a fix?

**Comment by jacebrowning** [comment]
@jasich Try deleting your local database (`dropdb memegen_dev`). It now uses migrations.

**Comment by jasich** [comment]
I think the typeahead text needs to change to a dark color so you can see it.  I'm out of town but I'll try to get to it tonight or tomorrow.  Otherwise the plan sounds good.

**Comment by jacebrowning** [comment]
If I can figure out where that is, I'll do it. Otherwise, check the status when you can.

**Comment by jacebrowning** [comment]
Remaining:

- https://github.com/jacebrowning/memegen/issues/181
- https://github.com/jacebrowning/memegen/issues/182
- https://github.com/jacebrowning/memegen/issues/183
- https://github.com/jacebrowning/memegen/issues/184

**Pull request merged**
