### PR TITLE
Adds Mistake Marvin 

### PR DESCRIPTION
**Pull request by Miterion**

### CODE REVIEW

**Comment by jacebrowning** [comment]
How would you feel about making the template directory name `mmm` and adding `mistake-marvin` to the list of aliases?

**Comment by Miterion** [comment]
Does mm as the directory name work too?

**Comment by jacebrowning** [comment]
That would work too. I think adding `mmm` as an alias would be helpful as it's the full initials of the meme.

**Comment by Miterion** [comment]
Changed the folder to mmm and the alias to mistake-marvin instead of marvin

**Pull request merged**
