### PR TITLE
Remove Windows related things

### PR DESCRIPTION
**Pull request by joshfriend**
Gunicorn and psycopg2 wont run on windows, so it seems rather pointless to indicate that this project can run in a windows environment.

### CODE REVIEW

**Comment by jacebrowning** [comment]
Thanks for pointing out these incompatibilities. I'd actually like to spend some time seeing if I can't get this to continue working on Windows so **anyone** can submit meme templates. This could be as simply as:

- use Flask's server for local development (or as a fallback)
- allow the app to run without extensions that require external resources

**Comment by jacebrowning** [comment]
I should probably also add a Windows CI service...

**Comment by jacebrowning** [comment]
We now have some form of Windows support via: https://github.com/jacebrowning/memegen/pull/194

**Comment by joshfriend** [comment]
I would assume that the ubuntu/bash integration in windows 10 could also open up some possibilities here as well.

**Comment by jacebrowning** [comment]
Definitely! I'm very curious to see what actually becomes of that. Will it support symlinks? Will it have access to normal Windows path? And many more questions...

**Pull request closed without merging**
