### PR TITLE
add loading gif while meme images load

### LINKED ISSUE #196: Add a placeholder loading indicator for images
The site will look nicer if it shows a loading animation for images.

### PR DESCRIPTION
**Pull request by GusCaplan**
closes #196

### CODE REVIEW

**Comment by GusCaplan** [comment]
@jacebrowning this is the real deal

**Comment by jacebrowning** [comment]
Hmm... I'm still not seeing it. Could you attach a screenshot of what the loading page looks like on your machine.

**Comment by GusCaplan** [comment]
@jacebrowning i named a css value incorrectly amma fix it now

**Comment by GusCaplan** [comment]
screen shot 2016-05-30 at 4 11 42 pm

**Comment by jacebrowning** [comment]
Weird, now I see it. Thanks!

**Pull request merged**
