### PR TITLE
Add 'width' and 'height' query params for images

### LINKED ISSUE #313: Allow custom image sizes
`?width=123` scales the image to have a width of 123 pixels.

`?height=456` scales the image to have a height of 456 pixels.

`?width=123&height=456` scales the image using the smaller dimension and fills the background to fit the other dimension.

### PR DESCRIPTION
**Pull request by jacebrowning**
Closes #313 

-----

- [x] Add `width` and `height` query params
- [x] Pad background with black

### CODE REVIEW

**Comment by jacebrowning** [comment]
@jasich This seems to be working: https://twitter.com/memegen_link/status/817926106019938304

**Comment by jasich** [comment]
That is the most beautiful thing I've seen today

**Comment by jacebrowning** [comment]
I'm going to work on making the share URL link back to the full-size image, then merge.

**Comment by jacebrowning** [comment]
Even with this change, Twitter still links to the original image.

**Pull request merged**
