### PR TITLE
Add 'magic' route to best-fit a meme

### PR DESCRIPTION
**Pull request by jacebrowning**
- [x] Add to root
- [x] Add route documentation
- [ ] Support POST
- [x] Add regexes to memes (as examples)
- [x] Redirect with dashes
- [x] Compile regexes on load

### CODE REVIEW

**Comment by GusCaplan** [comment]
@jacebrowning how do i use this? i tried
`http://memegen.link/magic/not-sure-if-bad/or-good`
and stuff like that
but it returns template not found

**Comment by jacebrowning** [comment]
It only takes a single string for the route: http://memegen.link/magic/not-sure-if-bad-or-good

**Comment by GusCaplan** [comment]
ahhhhh

**Comment by jacebrowning** [comment]
Depending on your system, you might be able to run the prototype of a GUI that takes advantage of this:

```
make gui
```

Eventually, I'd like to get a tab on the web UI that provides "live" results for entered text.

**Comment by GusCaplan** [comment]
this is great for my bot on discord. now i can make an auto generate.

**Pull request merged**
