### PR TITLE
Dokku support

### PR DESCRIPTION
**Pull request by esantoro**
Added/Enable Dokku personal Paas support.

Please review, and merge it if you like it :)

### CODE REVIEW

**Comment by jacebrowning** [comment]
Can you explain the purpose of this change a bit more? I'm not familiar with Dokku.

**Comment by esantoro** [comment]
Dokku (https://github.com/progrium/dokku) is a software for creating single-host paas platform.

This basically means that after you install dokku on your host, you get an heroku-like platform where you can push code and it will build it and deploy it almost automagically, just like Heroku.

I like dokku because it gives you the flexibility of heroku (utter pleasure when testing/experimenting) without... The bill at the end of the month.

I hope i was clear enough, otherwise feel free to ask more questions!

**Comment by esantoro** [comment]
Are you going to merge this or not.. ?

**Comment by esantoro** [comment]
Thanks!! :+1:

**Pull request merged**
